### ISSUE TITLE
Setup Does Not Save

### ISSUE THREAD

**Issue by Poikilos** [andrzuk/AngularCMS#3]
Hello,
I really like the layout and simplicity of this CMS. If I can get it working on my server I'd like to use it and possibly add improvements for you to merge. I understand it uses AngularJS (I understand it is different than Angular which uses TypeScript). Do you have any clues why setup would just spin after I push save on the initial setup? I have uploaded all of the files, and I am running setup. I tried to use php5 by adding the following to .htaccess but it didn't change the behavior:
```php
AddType application/x-httpd-php5 .php5 .php4 .php .php3 .php2 .phtml
AddHandler application/x-httpd-php5 .php5 .php4 .php .php3 .php2 .phtml
``` 
- If I hit refresh, it says I don't have permission to view /install/.
- If I go back to the main site, the blank setup page comes back.

**Comment by andrzuk** [comment]
Hello @poikilos, 
You must debug install script (https://github.com/andrzuk/AngularCMS/blob/master/install/install_database.php). And first of all check if your database connection variables (https://github.com/andrzuk/AngularCMS/blob/master/config/config.php) are correct.

**Comment by Poikilos** [comment]
Thanks, I'll test this. If it works, I'll close.

**Comment by Poikilos** [comment]
"Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint..."
I created install_database_debug.php based upon install_database.php, and did the following:
* Turn on error reporting:
```PHP
error_reporting(E_ALL);
ini_set('display_errors', 1);
```
* Split the constraints into separate queries
The the second foreign key constraint on `access_rights` **always fails**:
```SQL
		ALTER TABLE `access_rights`
		  ADD CONSTRAINT `fk_rights_users` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`);
```
It doesn't matter whether you switch it with the one before it, that one **always works**:
```SQL
		ALTER TABLE `access_rights`
		  ADD CONSTRAINT `fk_rights_resources` FOREIGN KEY (`resource_id`) REFERENCES `access_levels` (`id`);
```
It doesn't matter if you do them both at once either (it still fails with the same error on the PHP line that executes the SQL containing the `fk_rights_users` constraint).
I'm having a hard time figuring this out. I know SQL and database concepts, but I can't see how the first one would work and the other would not, considering that the previous SQL code seems to set up those fields in the same way:
```SQL
		CREATE TABLE `access_rights` (
		  `id` int(11) UNSIGNED NOT NULL,
		  `user_id` int(11) UNSIGNED NOT NULL,
		  `resource_id` int(11) UNSIGNED NOT NULL,
		  `access` tinyint(1) NOT NULL
		) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```
```SQL
		CREATE TABLE `users` (
			`id` int(11) unsigned NOT NULL,
			`login` varchar(100) NOT NULL,
			`password` varchar(100) NOT NULL,
			`email` varchar(128) NOT NULL,
			`role` smallint(3) unsigned NOT NULL,
			`active` tinyint(1) NOT NULL,
			`registered` datetime NOT NULL,
			`logged_in` datetime NOT NULL,
			`token` varchar(255) NOT NULL
			) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```
```SQL
		ALTER TABLE `access_rights`
		  ADD PRIMARY KEY (`id`),
		  ADD UNIQUE KEY `user_resource` (`user_id`, `resource_id`),
		  ADD KEY `fk_rights_resources` (`resource_id`),
		  ADD KEY `fk_rights_users` (`user_id`);

```
Do you have any ideas?

**Comment by andrzuk** [comment]
@poikilos ,
These constraints are not necessary for app running, so ommit them and ommit foreign keys like this:

		ALTER TABLE `access_rights`
				ADD PRIMARY KEY (`id`),
				ADD UNIQUE KEY `user_resource` (`user_id`, `resource_id`);

PS: Do you have "InnoDB" tables type? Because "InnoDB" allows using foreign keys, whilst "MyISAM" tables type does not.

**Comment by Poikilos** [comment]
> These constraints are not necessary for app running, so ommit them and ommit foreign keys

I rather fix it to enforce referential integrity.
* Any number of foreign keys should be allowed--when was the code last working, and on what version of MySQL?
* Was the code changed since it was working last?

> PS: Do you have "InnoDB" tables type? Because "InnoDB" allows using foreign keys, whilst "MyISAM" tables type does not.

InnoDB support is present, used by default, and used explicitly by AngularCMS SQL code. I checked for InnoDB support with the following:
```PHP
	$query = "SELECT SUPPORT FROM INFORMATION_SCHEMA.ENGINES WHERE ENGINE = 'InnoDB';";
	$statement = $db_connection->prepare($query);
	$innodb_support = null;
	$statement->execute();
	$rows = $statement->fetchAll(PDO::FETCH_ASSOC);
	if (count($rows) > 0) {
		if (array_key_exists("SUPPORT", $rows[0])) {
			$innodb_support = $rows[0]["SUPPORT"];
			echo "InnoDB SUPPORT: $innodb_support<br/>";  // ok: "YES" or "DEFAULT"; bad: "NO"
		}
		else echo "InnoDB SUPPORT: (bad result) " . json_encode($rows) . "<br/>";  // ok: "YES" or "DEFAULT"; bad: "NO"
	}
	else echo "InnoDB SUPPORT: (bad result) " . json_encode($rows) . "<br/>";  // ok: "YES" or "DEFAULT"; bad: "NO"

```
which yields:
```
InnoDB SUPPORT: DEFAULT
```
[install_database_debug (Change form_data before use).zip](https://github.com/andrzuk/AngularCMS/files/3207981/install_database_debug.Change.form_data.before.use.zip)

That can't be the problem anyway, because as I said, the first constraint always works (:edit: `fk_rights_users` fails no matter what order) when I split the constraints into two statements (all 8 constraints were in 1 statement before, and had the same error but harder to pin down, so I split them up in the attached version). Please consider my questions in the bullet points above.

**Comment by Poikilos** [comment]
* I've also ensured that they are both the same type (`int(11)`).
* I've verified that the user exists in the parent table via:
```PHP

	$query = "SELECT user_id FROM access_rights;";
	$statement = $db_connection->prepare($query);
	$this_id = null;
	$statement->execute();
	$rows = $statement->fetchAll(PDO::FETCH_ASSOC);
	$tried = array();
	if (count($rows) > 0) {
		for ($row_i=0; $row_i<count($rows); $row_i++) {
			if (array_key_exists("user_id", $rows[$row_i])) {
				$this_id = $rows[$row_i]["user_id"];
				if (!array_key_exists($this_id, $tried)) {
					$tried[$this_id] = true;
					echo "this_id: $this_id<br/>";  // ok: "YES" or "DEFAULT"; bad: "NO"
					$this_query = "SELECT id FROM users WHERE id = $this_id;";
					// echo "$query...<br/>";
					$this_statement = $db_connection->prepare($this_query);
					$id1 = null;
					$this_statement->execute();
					$this_rows = $this_statement->fetchAll(PDO::FETCH_ASSOC);
					if (count($this_rows) > 0) {
						if (array_key_exists("id", $this_rows[0])) {
							$id1 = $this_rows[0]["id"];
							echo "- found in users: $id1<br/>";  // ok: "YES" or "DEFAULT"; bad: "NO"
						}
						else echo "- not found in users: (bad result) " . json_encode($this_rows) . "<br/>";  // ok: "YES" or "DEFAULT"; bad: "NO"
					}
					else echo "- not found in users: (bad result) " . json_encode($this_rows) . "<br/>";  // ok: "YES" or "DEFAULT"; bad: "NO"
				}
			}
			else echo "access_rights.user_id [$row_i]: (bad result) " . json_encode($rows[$row_i]) . "<br/>";  // ok: "YES" or "DEFAULT"; bad: "NO"
		}
	}
	else echo "access_rights.user_id list: (bad result) " . json_encode($rows) . "<br/>";  // ok: "YES" or "DEFAULT"; bad: "NO"
```
which yields:
```
this_id: 1
- found in users: 1
```

**Comment by andrzuk** [comment]
Considering your questions:

> Any number of foreign keys should be allowed--when was the code last working, and on what version of MySQL?

Foreign keys are not required by app. They are used only as additional protection of database integrity. Application takes care of data consistency by itself. So you can create database tables manually without any constraint.
On my hosting version of MySQL is 5.6.36.

> Was the code changed since it was working last?

Yes, but only private version with dedicated functionality, not present on GitHub.

**Comment by Poikilos** [comment]
Understood. I'll implement the workaround and submit a pull request if you don't get there before me.
